package com.gollum.jammyfurniture.inits;

import com.gollum.jammyfurniture.common.crafting.DishwasherRecipes;
import com.gollum.jammyfurniture.common.crafting.WashingMachineRecipes;

import cpw.mods.fml.common.Loader;

public class ModRecipesCompatibility {

	public static void init() {
		
		if (Loader.isModLoaded("Aquaculture")) {
			DishwasherRecipes.smelting().addSmelting("Aquaculture:item.IronFishingRod"   , 1500);
			DishwasherRecipes.smelting().addSmelting("Aquaculture:item.GoldFishingRod"   , 6000);
			DishwasherRecipes.smelting().addSmelting("Aquaculture:item.DiamondFishingRod", 7200);
			DishwasherRecipes.smelting().addSmelting("Aquaculture:item.NeptuniumPickaxe" , 8000);
			DishwasherRecipes.smelting().addSmelting("Aquaculture:item.NeptuniumShovel"  , 8000);
			DishwasherRecipes.smelting().addSmelting("Aquaculture:item.NeptuniumAxe"     , 8000);
			DishwasherRecipes.smelting().addSmelting("Aquaculture:item.NeptuniumHoe"     , 8000);
			DishwasherRecipes.smelting().addSmelting("Aquaculture:item.NeptuniumSword"   , 8000);
			
			WashingMachineRecipes.smelting().addSmelting("Aquaculture:item.NeptuniumHelmet", 7200);
			WashingMachineRecipes.smelting().addSmelting("Aquaculture:item.NeptuniumPlate", 7200);
			WashingMachineRecipes.smelting().addSmelting("Aquaculture:item:NeptuniumLegs", 7200);
			WashingMachineRecipes.smelting().addSmelting("Aquaculture:item:NeptuniumBoots", 7200);
		}
		
		if (Loader.isModLoaded("BiomesOPlenty")) {
			DishwasherRecipes.smelting().addSmelting("BiomesOPlenty:scytheWood", 1500);
			DishwasherRecipes.smelting().addSmelting("BiomesOPlenty:scytheStone", 4000);
			DishwasherRecipes.smelting().addSmelting("BiomesOPlenty:scytheIron", 4800);
			DishwasherRecipes.smelting().addSmelting("BiomesOPlenty:scytheGold", 6000);
			DishwasherRecipes.smelting().addSmelting("BiomesOPlenty:scytheDiamond", 7200);
			DishwasherRecipes.smelting().addSmelting("BiomesOPlenty:scytheMud", 7800);
			DishwasherRecipes.smelting().addSmelting("BiomesOPlenty:scytheAmethyst", 7600);
			DishwasherRecipes.smelting().addSmelting("BiomesOPlenty:swordAmethyst", 7600);
			DishwasherRecipes.smelting().addSmelting("BiomesOPlenty:shovelAmethyst", 7600);
			DishwasherRecipes.smelting().addSmelting("BiomesOPlenty:pickaxeAmethyst", 7600);
			DishwasherRecipes.smelting().addSmelting("BiomesOPlenty:axeAmethyst", 7600);
			DishwasherRecipes.smelting().addSmelting("BiomesOPlenty:hoeAmethyst", 7600);
			DishwasherRecipes.smelting().addSmelting("BiomesOPlenty:swordMud", 7800);
			DishwasherRecipes.smelting().addSmelting("BiomesOPlenty:shovelMud", 7800);
			DishwasherRecipes.smelting().addSmelting("BiomesOPlenty:pickaxeMud", 7800);
			DishwasherRecipes.smelting().addSmelting("BiomesOPlenty:axeMud", 7800);
			DishwasherRecipes.smelting().addSmelting("BiomesOPlenty:hoeMud", 7800);
			
			WashingMachineRecipes.smelting().addSmelting("BiomesOPlenty:helmetAmethyst", 7600);
			WashingMachineRecipes.smelting().addSmelting("BiomesOPlenty:chestplateAmethyst", 7600);
			WashingMachineRecipes.smelting().addSmelting("BiomesOPlenty:leggingsAmethyst", 7600);
			WashingMachineRecipes.smelting().addSmelting("BiomesOPlenty:bootsAmethyst", 7600);
		}
		
		if (Loader.isModLoaded("Oceancraft")) {
			DishwasherRecipes.smelting().addSmelting("Oceancraft:CoralHoe", 7400);
			DishwasherRecipes.smelting().addSmelting("Oceancraft:CoralSword", 7400);
			DishwasherRecipes.smelting().addSmelting("Oceancraft:CoralPickaxe", 7400);
			DishwasherRecipes.smelting().addSmelting("Oceancraft:CoralAxe", 7400);
			DishwasherRecipes.smelting().addSmelting("Oceancraft:CoralShovel", 7400);
			
			WashingMachineRecipes.smelting().addSmelting("Oceancraft:CoralHelmet", 7400);
			WashingMachineRecipes.smelting().addSmelting("Oceancraft:CoralBody", 7400);
			WashingMachineRecipes.smelting().addSmelting("Oceancraft:CoralPants", 7400);
			WashingMachineRecipes.smelting().addSmelting("Oceancraft:CoralBoots", 7400);
		}
		
		if (Loader.isModLoaded("Thaumcraft")) {
			DishwasherRecipes.smelting().addSmelting("Thaumcraft:ItemShovelThaumium", 7400);
			DishwasherRecipes.smelting().addSmelting("Thaumcraft:ItemPickThaumium", 7400);
			DishwasherRecipes.smelting().addSmelting("Thaumcraft:ItemAxeThaumium", 7400);
			DishwasherRecipes.smelting().addSmelting("Thaumcraft:ItemSwordThaumium", 7400);
			DishwasherRecipes.smelting().addSmelting("Thaumcraft:ItemHoeThaumium", 7400);
			DishwasherRecipes.smelting().addSmelting("Thaumcraft:ItemSwordElemental", 7600);
			DishwasherRecipes.smelting().addSmelting("Thaumcraft:ItemShovelElemental", 7600);
			DishwasherRecipes.smelting().addSmelting("Thaumcraft:ItemPickaxeElemental", 7600);
			DishwasherRecipes.smelting().addSmelting("Thaumcraft:ItemAxeElemental", 7600);
			DishwasherRecipes.smelting().addSmelting("Thaumcraft:ItemHoeElemental", 7600);
			DishwasherRecipes.smelting().addSmelting("Thaumcraft:ItemShovelVoid", 8200);
			DishwasherRecipes.smelting().addSmelting("Thaumcraft:ItemPickVoid", 8200);
			DishwasherRecipes.smelting().addSmelting("Thaumcraft:ItemAxeVoid", 8200);
			DishwasherRecipes.smelting().addSmelting("Thaumcraft:ItemSwordVoid", 8200);
			DishwasherRecipes.smelting().addSmelting("Thaumcraft:ItemHoeVoid", 8200);
			
			WashingMachineRecipes.smelting().addSmelting("Thaumcraft:ItemHelmetThaumium", 7400);
			WashingMachineRecipes.smelting().addSmelting("Thaumcraft:ItemChestplateThaumium", 7400);
			WashingMachineRecipes.smelting().addSmelting("Thaumcraft:ItemLeggingsThaumium", 7400);
			WashingMachineRecipes.smelting().addSmelting("Thaumcraft:ItemBootsThaumium", 7400);
			WashingMachineRecipes.smelting().addSmelting("Thaumcraft:ItemHelmetVoid", 8200);
			WashingMachineRecipes.smelting().addSmelting("Thaumcraft:ItemChestplateVoid", 8200);
			WashingMachineRecipes.smelting().addSmelting("Thaumcraft:ItemLeggingsVoid", 8200);
			WashingMachineRecipes.smelting().addSmelting("Thaumcraft:ItemBootsVoid", 8200);
		}

		if (Loader.isModLoaded("Railcraft")) {
			DishwasherRecipes.smelting().addSmelting("Railcraft:tool.steel.shears", 6800);
			DishwasherRecipes.smelting().addSmelting("Railcraft:tool.steel.sword", 6800);
			DishwasherRecipes.smelting().addSmelting("Railcraft:tool.steel.shovel", 6800);
			DishwasherRecipes.smelting().addSmelting("Railcraft:tool.steel.pickaxe", 6800);
			DishwasherRecipes.smelting().addSmelting("Railcraft:tool.steel.axe", 6800);
			DishwasherRecipes.smelting().addSmelting("Railcraft:tool.steel.hoe", 6800);
			
			WashingMachineRecipes.smelting().addSmelting("Railcraft:armor.steel.helmet", 6800);
			WashingMachineRecipes.smelting().addSmelting("Railcraft:armor.steel.plate", 6800);
			WashingMachineRecipes.smelting().addSmelting("Railcraft:armor.steel.legs", 6800);
			WashingMachineRecipes.smelting().addSmelting("Railcraft:armor.steel.boots", 6800);
			WashingMachineRecipes.smelting().addSmelting("Railcraft:armor.overalls", 6800);
		}

		if (Loader.isModLoaded("TwilightForest")) {
			DishwasherRecipes.smelting().addSmelting("TwilightForest:item.ironwoodSword", 7200);
			DishwasherRecipes.smelting().addSmelting("TwilightForest:item.ironwoodShovel", 7200);
			DishwasherRecipes.smelting().addSmelting("TwilightForest:item.ironwoodPick", 7200);
			DishwasherRecipes.smelting().addSmelting("TwilightForest:item.ironwoodAxe", 7200);
			DishwasherRecipes.smelting().addSmelting("TwilightForest:item.ironwoodHoe", 7200);
			DishwasherRecipes.smelting().addSmelting("TwilightForest:item.fierySword", 7200);
			DishwasherRecipes.smelting().addSmelting("TwilightForest:item.fieryPick", 7200);
			DishwasherRecipes.smelting().addSmelting("TwilightForest:item.steeleafSword", 7200);
			DishwasherRecipes.smelting().addSmelting("TwilightForest:item.steeleafShovel", 7200);
			DishwasherRecipes.smelting().addSmelting("TwilightForest:item.steeleafPick", 7200);
			DishwasherRecipes.smelting().addSmelting("TwilightForest:item.steeleafAxe", 7200);
			DishwasherRecipes.smelting().addSmelting("TwilightForest:item.steeleafHoe", 7200);
			DishwasherRecipes.smelting().addSmelting("TwilightForest:item.knightlySword", 7200);
			DishwasherRecipes.smelting().addSmelting("TwilightForest:item.knightlyPick", 7200);
			DishwasherRecipes.smelting().addSmelting("TwilightForest:item.knightlyAxe", 7200);
			
			WashingMachineRecipes.smelting().addSmelting("TwilightForest:item.ironwoodHelm", 7200);
			WashingMachineRecipes.smelting().addSmelting("TwilightForest:item.ironwoodPlate", 7200);
			WashingMachineRecipes.smelting().addSmelting("TwilightForest:item.ironwoodLegs", 7200);
			WashingMachineRecipes.smelting().addSmelting("TwilightForest:item.ironwoodBoots", 7200);
			WashingMachineRecipes.smelting().addSmelting("TwilightForest:item.fieryHelm", 7200);
			WashingMachineRecipes.smelting().addSmelting("TwilightForest:item.fieryPlate", 7200);
			WashingMachineRecipes.smelting().addSmelting("TwilightForest:item.fieryLegs", 7200);
			WashingMachineRecipes.smelting().addSmelting("TwilightForest:item.fieryBoots", 7200);
			WashingMachineRecipes.smelting().addSmelting("TwilightForest:item.steeleafHelm", 7200);
			WashingMachineRecipes.smelting().addSmelting("TwilightForest:item.steeleafPlate", 7200);
			WashingMachineRecipes.smelting().addSmelting("TwilightForest:item.steeleafLegs", 7200);
			WashingMachineRecipes.smelting().addSmelting("TwilightForest:item.steeleafBoots", 7200);
			WashingMachineRecipes.smelting().addSmelting("TwilightForest:item.knightlyHelm", 7200);
			WashingMachineRecipes.smelting().addSmelting("TwilightForest:item.knightlyPlate", 7200);
			WashingMachineRecipes.smelting().addSmelting("TwilightForest:item.knightlyLegs", 7200);
			WashingMachineRecipes.smelting().addSmelting("TwilightForest:item.knightlyBoots", 7200);
			WashingMachineRecipes.smelting().addSmelting("TwilightForest:item.yetiHelm", 7200);
			WashingMachineRecipes.smelting().addSmelting("TwilightForest:item.yetiPlate", 7200);
			WashingMachineRecipes.smelting().addSmelting("TwilightForest:item.yetiLegs", 7200);
			WashingMachineRecipes.smelting().addSmelting("TwilightForest:item.yetiBoots", 7200);
			WashingMachineRecipes.smelting().addSmelting("TwilightForest:item.arcticHelm", 7200);
			WashingMachineRecipes.smelting().addSmelting("TwilightForest:item.arcticPlate", 7200);
			WashingMachineRecipes.smelting().addSmelting("TwilightForest:item.arcticLegs", 7200);
			WashingMachineRecipes.smelting().addSmelting("TwilightForest:item.arcticBoots", 7200);
		}
		if (Loader.isModLoaded("weaponmod")) {
			DishwasherRecipes.smelting().addSmelting("weaponmod:spear.wood", 1500);
			DishwasherRecipes.smelting().addSmelting("weaponmod:spear.stone", 4000);
			DishwasherRecipes.smelting().addSmelting("weaponmod:spear.iron", 4800);
			DishwasherRecipes.smelting().addSmelting("weaponmod:spear.gold", 6000);
			DishwasherRecipes.smelting().addSmelting("weaponmod:spear.diamond", 7200);
			DishwasherRecipes.smelting().addSmelting("weaponmod:halberd.wood", 1500);
			DishwasherRecipes.smelting().addSmelting("weaponmod:halberd.stone", 4000);
			DishwasherRecipes.smelting().addSmelting("weaponmod:halberd.iron", 4800);
			DishwasherRecipes.smelting().addSmelting("weaponmod:halberd.gold", 6000);
			DishwasherRecipes.smelting().addSmelting("weaponmod:halberd.diamond", 7200);
			DishwasherRecipes.smelting().addSmelting("weaponmod:battleaxe.wood", 1500);
			DishwasherRecipes.smelting().addSmelting("weaponmod:battleaxe.stone", 4000);
			DishwasherRecipes.smelting().addSmelting("weaponmod:battleaxe.iron", 4800);
			DishwasherRecipes.smelting().addSmelting("weaponmod:battleaxe.gold", 6000);
			DishwasherRecipes.smelting().addSmelting("weaponmod:battleaxe.diamond", 7200);
			DishwasherRecipes.smelting().addSmelting("weaponmod:knife.wood", 1500);
			DishwasherRecipes.smelting().addSmelting("weaponmod:knife.stone", 4000);
			DishwasherRecipes.smelting().addSmelting("weaponmod:knife.iron", 4800);
			DishwasherRecipes.smelting().addSmelting("weaponmod:knife.gold", 6000);
			DishwasherRecipes.smelting().addSmelting("weaponmod:knife.diamond", 7200);
			DishwasherRecipes.smelting().addSmelting("weaponmod:warhammer.wood", 1500);
			DishwasherRecipes.smelting().addSmelting("weaponmod:warhammer.stone", 4000);
			DishwasherRecipes.smelting().addSmelting("weaponmod:warhammer.iron", 4800);
			DishwasherRecipes.smelting().addSmelting("weaponmod:warhammer.gold", 6000);
			DishwasherRecipes.smelting().addSmelting("weaponmod:warhammer.diamond", 7200);
			DishwasherRecipes.smelting().addSmelting("weaponmod:flail.wood", 1500);
			DishwasherRecipes.smelting().addSmelting("weaponmod:flail.stone", 4000);
			DishwasherRecipes.smelting().addSmelting("weaponmod:flail.iron", 4800);
			DishwasherRecipes.smelting().addSmelting("weaponmod:flail.gold", 6000);
			DishwasherRecipes.smelting().addSmelting("weaponmod:flail.diamond", 7200);
			DishwasherRecipes.smelting().addSmelting("weaponmod:katana.wood", 1500);
			DishwasherRecipes.smelting().addSmelting("weaponmod:katana.stone", 4000);
			DishwasherRecipes.smelting().addSmelting("weaponmod:katana.iron", 4800);
			DishwasherRecipes.smelting().addSmelting("weaponmod:katana.gold", 6000);
			DishwasherRecipes.smelting().addSmelting("weaponmod:katana.diamond", 7200);
			DishwasherRecipes.smelting().addSmelting("weaponmod:boomerang.wood", 1500);
			DishwasherRecipes.smelting().addSmelting("weaponmod:boomerang.stone", 4000);
			DishwasherRecipes.smelting().addSmelting("weaponmod:boomerang.iron", 4800);
			DishwasherRecipes.smelting().addSmelting("weaponmod:boomerang.gold", 6000);
			DishwasherRecipes.smelting().addSmelting("weaponmod:boomerang.diamond", 7200);
			DishwasherRecipes.smelting().addSmelting("weaponmod:crossbow", 7200);
			DishwasherRecipes.smelting().addSmelting("weaponmod:musket", 7200);
			DishwasherRecipes.smelting().addSmelting("weaponmod:musketbayonet.wood", 1500);
			DishwasherRecipes.smelting().addSmelting("weaponmod:musketbayonet.stone", 4000);
			DishwasherRecipes.smelting().addSmelting("weaponmod:musketbayonet.iron", 4800);
			DishwasherRecipes.smelting().addSmelting("weaponmod:musketbayonet.gold", 6000);
			DishwasherRecipes.smelting().addSmelting("weaponmod:musketbayonet.diamond", 7200);
			DishwasherRecipes.smelting().addSmelting("weaponmod:flintlock", 7200);
			DishwasherRecipes.smelting().addSmelting("weaponmod:cannon", 7200);
		}
		
		if (Loader.isModLoaded("colorfularmor")) {
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:RedIronHelmet", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:RedIronPlate", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:RedIronLeggings", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:RedIronBoots", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GreenIronHelmet", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GreenIronPlate", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GreenIronLeggings", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GreenIronBoots", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlackIronHelmet", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlackIronPlate", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlackIronLeggings", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlackIronBoots", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:TurquoiseIronHelmet", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:TurquoiseIronPlate", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:TurquoiseIronLeggings", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:TurquoiseIronBoots", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PinkIronHelmet", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PinkIronPlate", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PinkIronLeggings", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PinkIronBoots", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlueIronHelmet", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlueIronPlate", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlueIronLeggings", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlueIronBoots", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightBlueIronHelmet", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightBlueIronPlate", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightBlueIronLeggings", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightBlueIronBoots", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGreenIronHelmet", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGreenIronPlate", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGreenIronLeggings", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGreenIronBoots", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:YellowIronHelmet", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:YellowIronPlate", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:YellowIronLeggings", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:YellowIronBoots", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PurpleIronHelmet", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PurpleIronPlate", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PurpleIronLeggings", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PurpleIronBoots", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:OrangeIronHelmet", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:OrangeIronPlate", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:OrangeIronLeggings", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:OrangeIronBoots", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:WhiteIronHelmet", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:WhiteIronPlate", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:WhiteIronLeggings", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:WhiteIronBoots", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BrownIronHelmet", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BrownIronPlate", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BrownIronLeggings", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BrownIronBoots", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:MagentaIronHelmet", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:MagentaIronPlate", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:MagentaIronLeggings", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:MagentaIronBoots", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GrayIronHelmet", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GrayIronPlate", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GrayIronLeggings", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GrayIronBoots", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGrayIronHelmet", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGrayIronPlate", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGrayIronLeggings", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGrayIronBoots", 4000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:RedGoldHelmet", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:RedGoldPlate", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:RedGoldLeggings", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:RedGoldBoots", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GreenGoldHelmet", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GreenGoldPlate", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GreenGoldLeggings", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GreenGoldBoots", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlackGoldHelmet", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlackGoldPlate", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlackGoldLeggings", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlackGoldBoots", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:TurquoiseGoldHelmet", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:TurquoiseGoldPlate", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:TurquoiseGoldLeggings", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:TurquoiseGoldBoots", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PinkGoldHelmet", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PinkGoldPlate", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PinkGoldLeggings", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PinkGoldBoots", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlueGoldHelmet", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlueGoldPlate", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlueGoldLeggings", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlueGoldBoots", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightBlueGoldHelmet", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightBlueGoldPlate", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightBlueGoldLeggings", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightBlueGoldBoots", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGreenGoldHelmet", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGreenGoldPlate", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGreenGoldLeggings", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGreenGoldBoots", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:YellowGoldHelmet", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:YellowGoldPlate", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:YellowGoldLeggings", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:YellowGoldBoots", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PurpleGoldHelmet", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PurpleGoldPlate", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PurpleGoldLeggings", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PurpleGoldBoots", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:OrangeGoldHelmet", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:OrangeGoldPlate", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:OrangeGoldLeggings", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:OrangeGoldBoots", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:WhiteGoldHelmet", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:WhiteGoldPlate", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:WhiteGoldLeggings", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:WhiteGoldBoots", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BrownGoldHelmet", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BrownGoldPlate", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BrownGoldLeggings", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BrownGoldBoots", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:MagentaGoldHelmet", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:MagentaGoldPlate", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:MagentaGoldLeggings", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:MagentaGoldBoots", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GrayGoldHelmet", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GrayGoldPlate", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GrayGoldLeggings", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GrayGoldBoots", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGrayGoldHelmet", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGrayGoldPlate", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGrayGoldLeggings", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGrayGoldBoots", 4800);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:RedDiamondHelmet", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:RedDiamondPlate", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:RedDiamondLeggings", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:RedDiamondBoots", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GreenDiamondHelmet", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GreenDiamondPlate", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GreenDiamondLeggings", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GreenDiamondBoots", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlackDiamondHelmet", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlackDiamondPlate", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlackDiamondLeggings", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlackDiamondBoots", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:TurquoiseDiamondHelmet", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:TurquoiseDiamondPlate", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:TurquoiseDiamondLeggings", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:TurquoiseDiamondBoots", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PinkDiamondHelmet", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PinkDiamondPlate", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PinkDiamondLeggings", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PinkDiamondBoots", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlueDiamondHelmet", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlueDiamondPlate", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlueDiamondLeggings", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlueDiamondBoots", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightBlueDiamondHelmet", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightBlueDiamondPlate", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightBlueDiamondLeggings", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightBlueDiamondBoots", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGreenDiamondHelmet", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGreenDiamondPlate", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGreenDiamondLeggings", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGreenDiamondBoots", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:YellowDiamondHelmet", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:YellowDiamondPlate", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:YellowDiamondLeggings", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:YellowDiamondBoots", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PurpleDiamondHelmet", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PurpleDiamondPlate", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PurpleDiamondLeggings", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PurpleDiamondBoots", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:OrangeDiamondHelmet", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:OrangeDiamondPlate", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:OrangeDiamondLeggings", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:OrangeDiamondBoots", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:WhiteDiamondHelmet", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:WhiteDiamondPlate", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:WhiteDiamondLeggings", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:WhiteDiamondBoots", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BrownDiamondHelmet", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BrownDiamondPlate", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BrownDiamondLeggings", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BrownDiamondBoots", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:MagentaDiamondHelmet", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:MagentaDiamondPlate", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:MagentaDiamondLeggings", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:MagentaDiamondBoots", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GrayDiamondHelmet", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GrayDiamondPlate", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GrayDiamondLeggings", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GrayDiamondBoots", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGrayDiamondHelmet", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGrayDiamondPlate", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGrayDiamondLeggings", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGrayDiamondBoots", 7200);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:RedChainHelmet", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:RedChainPlate", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:RedChainLeggings", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:RedChainBoots", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GreenChainHelmet", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GreenChainPlate", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GreenChainLeggings", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GreenChainBoots", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlackChainHelmet", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlackChainPlate", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlackChainLeggings", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlackChainBoots", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:TurquoiseChainHelmet", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:TurquoiseChainPlate", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:TurquoiseChainLeggings", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:TurquoiseChainBoots", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PinkChainHelmet", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PinkChainPlate", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PinkChainLeggings", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PinkChainBoots", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlueChainHelmet", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlueChainPlate", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlueChainLeggings", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BlueChainBoots", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightBlueChainHelmet", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightBlueChainPlate", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightBlueChainLeggings", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightBlueChainBoots", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGreenChainHelmet", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGreenChainPlate", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGreenChainLeggings", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGreenChainBoots", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:YellowChainHelmet", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:YellowChainPlate", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:YellowChainLeggings", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:YellowChainBoots", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PurpleChainHelmet", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PurpleChainPlate", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PurpleChainLeggings", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:PurpleChainBoots", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:OrangeChainHelmet", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:OrangeChainPlate", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:OrangeChainLeggings", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:OrangeChainBoots", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:WhiteChainHelmet", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:WhiteChainPlate", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:WhiteChainLeggings", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:WhiteChainBoots", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BrownChainHelmet", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BrownChainPlate", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BrownChainLeggings", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:BrownChainBoots", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:MagentaChainHelmet", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:MagentaChainPlate", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:MagentaChainLeggings", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:MagentaChainBoots", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GrayChainHelmet", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GrayChainPlate", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GrayChainLeggings", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:GrayChainBoots", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGrayChainHelmet", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGrayChainPlate", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGrayChainLeggings", 6000);
			WashingMachineRecipes.smelting().addSmelting("colorfularmor:LightGrayChainBoots", 6000);
		}
		if (Loader.isModLoaded("Paintball")) {
			WashingMachineRecipes.smelting().addSmelting("Paintball:Shoes (C)", 7200);
			WashingMachineRecipes.smelting().addSmelting("Paintball:Helmet (C)", 7200);
			WashingMachineRecipes.smelting().addSmelting("Paintball:Pants (C)", 7200);
			WashingMachineRecipes.smelting().addSmelting("Paintball:Chest (C)", 7200);
		}
		
		if (Loader.isModLoaded("ProjectZulu|Core")) {
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:ScaleHelmet", 7200);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:ScaleChest", 7200);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:ScaleLegs", 7200);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:ScaleBoots", 7200);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:GoldScaleHelmet", 4800);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:GoldScaleChest", 4800);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:GoldScaleLegs", 4800);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:GoldScaleBoots", 4800);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:IronScaleHelmet", 4000);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:IronScaleChest", 4000);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:IronScaleLegs", 4000);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:IronScaleBoots", 4000);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:DiamondScaleHelmet", 7200);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:DiamondScaleChest", 7200);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:DiamondScaleBoots", 7200);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:DiamondScaleLegs", 7200);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:RedClothHelmet", 7200);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:RedClothChest", 7200);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:RedClothLegs", 7200);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:RedClothBoots", 7200);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:GreenClothHelmet", 7200);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:GreenClothChest", 7200);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:GreenClothLegs", 7200);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:GreenClothBoots", 7200);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:BlueClothHelmet", 7200);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:BlueClothChest", 7200);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:BlueClothLegs", 7200);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:BlueClothBoots", 7200);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:CactusHelmet", 7200);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:CactusChest", 7200);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:CactusLegs", 7200);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:CactusBoots", 7200);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:FurHelmet", 7200);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:FurChest", 7200);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:FurLegs", 7200);
			WashingMachineRecipes.smelting().addSmelting("ProjectZulu|Core:FurBoots", 7200);
		}

	}

}
